kind: pipeline
type: docker
name: CI/CD Pipeline

steps:
  - name: Build Docker Image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      context: .
      repo: your-docker-repo/app
      tags: latest
      cache_from: your-docker-repo/app:latest
    when:
      event: [push]

  - name: Deploy with Docker Compose
    image: alpine/bundle-docker-compose
    commands:
      - docker-compose down
      - docker-compose up -d
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    depends_on:
      - Build Docker Image
    when:
      event: [push]

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
