kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

steps:
  - name: list root of repo inside container
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker run --rm -v /drone/src:/mnt alpine sh -c "ls -la /mnt"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
