kind: pipeline
type: exec
name: build-and-run

platform:
  os: linux
  arch: amd64

steps:
  - name: build-app
    commands:
      - echo "Собираем Docker-образ приложения"
      - docker build -t bookstore-app .

  - name: run-with-compose
    commands:
      - echo "Запускаем приложение с PostgreSQL через docker-compose"
      - docker-compose up -d
