kind: pipeline
type: docker
name: default

steps:
#  - name: cleanup docker state
#    image: docker
#    volumes:
#      - name: dockersock
#        path: /var/run/docker.sock
#    commands:
#      - docker-compose down -v || true
#      - docker container prune -f || true
#      - docker image prune -f || true

#  - name: build bookstore app
#    image: docker
#    volumes:
#      - name: dockersock
#        path: /var/run/docker.sock
#    commands:
#      - docker build -t bookstore-app .

#  - name: run bookstore API
#    image: docker/compose:1.29.2
#    volumes:
#      - name: dockersock
#        path: /var/run/docker.sock
#    commands:
#      - docker-compose up -d --build

#  - name: test
#    image: docker
#    volumes:
#      - name: dockersock
#        path: /var/run/docker.sock
#    commands:
#      - docker run --rm -i alpine sh -c "cat - > test.js; cat test.js" < /drone/src/k6/script.js

  - name: run load testing metrics plugin
    image: docker
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - cat /drone/src/k6/script.js
      - docker pull swezeg/loadtestingmetricsplugin:latest
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --privileged swezeg/loadtestingmetricsplugin:latest < /drone/src/k6/script.js

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
