kind: pipeline
type: docker
name: simple-pipeline

steps:
  - name: build bookStore app
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t bookstore-app .

  - name: run bookStore API
    image: docker/compose:1.29.2
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose up -d --build
  
  - name: run load testing metrics plugin
    image: swezeg/loadtestingmetricsplugin:2.0
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      SUBSCRIBE_TELEGRAM: true
      TELEGRAM_TOKEN: 8060387975:AAGTxAHHqHZo7LKpD4z7aLKx7LEZSngh8k8
      TELEGRAM_CHAT_ID: 958007638
      SENDING_FORMAT: TEXT_FORMAT
      ONLY_CURRENT_TEST: true

  - name: profile loadtesting plugin
    image: your/async-profiler-image:latest
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - CONTAINER=$(docker ps -q --filter ancestor=swezeg/loadtestingmetricsplugin:2.0)
      - PID=$(docker exec $CONTAINER pidof java)
      - docker exec --privileged $CONTAINER \
          /opt/async-profiler/profiler.sh -e cpu -d 30 -f /tmp/profile.html $PID
      - docker cp $CONTAINER:/tmp/profile.html .
      
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
