kind: pipeline
type: docker
name: simple-pipeline

steps:
  - name: run-docker-with-k6
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker run --rm --network=host -v /var/run/docker.sock:/var/run/docker.sock --privileged -e SUBSCRIBE_TELEGRAM="true" -e TELEGRAM_TOKEN="8060387975:AAGTxAHHqHZo7LKpD4z7aLKx7LEZSngh8k8" -e TELEGRAM_CHAT_ID="958007638" -e SENDING_FORMAT="TEXT_FORMAT" -e ONLY_CURRENT_TEST="true" swezeg/loadtestingmetricsplugin:latest
      
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
