kind: pipeline
type: docker
name: simple-pipeline

steps:
  - name: run-docker-with-k6
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: source
        path: /drone/src
    commands:
      - docker run --rm -v /drone/src/k6:/app alpine sh -c "ls -la /app"
      
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: source
    host:
      path: /drone/src
