kind: pipeline
type: exec
name: default

steps:
  - name: build API image
    commands:
      - docker build -t bookstore-app .

  - name: start infrastructure
    commands:
      - docker-compose up -d
