kind: pipeline
type: docker
name: simple-pipeline

steps:
  - name: run-docker-with-k6
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker run --rm -v /home/andrey:/app alpine sh -c "ls -la /app"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
